[package]
name = "discord-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
flate2 = "1.0"
tar = "0.4"
anyhow = "1.0"
libc = "0.2"
clap = { version = "4.0", features = ["derive"] }
